### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'

### ISSUE THREAD

**Issue by iGroza** [timeweb-cloud/twc#1]
# Description
I encountered an error while trying to execute the twc command in the terminal. I installed twc using pip3.

# Error Traceback
```sh
Traceback (most recent call last):
  File "/Users/igroza/Library/Python/3.9/bin/twc", line 5, in <module>
    from twc.__main__ import cli
  File "/Users/igroza/Library/Python/3.9/lib/python/site-packages/twc/__init__.py", line 5, in <module>
    from .api import TimewebCloud
  File "/Users/igroza/Library/Python/3.9/lib/python/site-packages/twc/api/__init__.py", line 3, in <module>
    from .client import TimewebCloud
  File "/Users/igroza/Library/Python/3.9/lib/python/site-packages/twc/api/client.py", line 8, in <module>
    from .base import TimewebCloudBase
  File "/Users/igroza/Library/Python/3.9/lib/python/site-packages/twc/api/base.py", line 10, in <module>
    from . import exceptions as exc
  File "/Users/igroza/Library/Python/3.9/lib/python/site-packages/twc/api/exceptions.py", line 9, in <module>
    class ErrResponse:
  File "/Users/igroza/Library/Python/3.9/lib/python/site-packages/twc/api/exceptions.py", line 16, in ErrResponse
    message: str | List[str] = None,
TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'

```

# Environment
pip: 23.1.2
Python: 3.9.6
Operating System: Mac OS 13.3.1
Processor: Apple M1

Please help me resolve this issue. Thank you!

**Comment by timeweb-cloud** [comment]
Thanks for the detailed report! Bug fixed in version [2.0.1](https://github.com/timeweb-cloud/twc/releases/tag/v2.0.1). Please update:
```
pip3 install --upgrade twc-cli
```
