### ISSUE TITLE
Undefined behavior on empty flags in "twc server get"

### ISSUE THREAD

**Issue by alpineQ** [timeweb-cloud/twc#5]
```sh
twc server get 3061871
```
```
Traceback (most recent call last):

  File "./venv/bin/twc", line 8, in <module>
    sys.exit(cli())
             ^^^^^

  File "./venv/lib/python3.12/site-packages/twc/commands/server.py", line 258, in server_get
    fmt.printer(response, output_format=output_format, func=print_server)

  File "./venv/lib/python3.12/site-packages/twc/fmt.py", line 131, in printer
    to_print.print(output_format, func=func, **kwargs)

  File "./venv/lib/python3.12/site-packages/twc/fmt.py", line 116, in print
    func(self._data, **kwargs)

  File "./venv/lib/python3.12/site-packages/twc/commands/server.py", line 155, in print_server
    main_ipv4,
    ^^^^^^^^^

UnboundLocalError: cannot access local variable 'main_ipv4' where it is not associated with a value
```
I think either cli should state that at least one flag is required or handle no flags situation by wrapping it with some sort of try-except

**Comment by timeweb-cloud** [comment]
Fixed in release 2.5.0.
